const SongActionTypes = {
  SET_SONGS: "SET_SONGS",
  SET_SONG_BY_ID: "SET_SONG_BY_ID",
  ADD_SONG: "ADD_SONG",
  EDIT_SONG: "EDIT_SONG",
  DELETE_SONG_START: "DELETE_SONG_START",
  DELETE_SONG_FINISH: "DELETE_SONG_FINISH",
  DELETE_SONG_CANCEL: "DELETE_SONG_CANCEL",
};

export default SongActionTypes;
