const ThemeActionTypes = {
  TOGGLE_DARK_MODE: "TOGGLE_DARK_MODE",
  SHOW_TOAST_NOTIFICATION: "SHOW_TOAST_NOTIFICATION",
  HIDE_TOAST_NOTIFICATION: "HIDE_TOAST_NOTIFICATION",
};

export default ThemeActionTypes;
