const PurchasesActionTypes = {
  GET_PURCHASES: "GET_PURCHASES",
  ADD_PURCHASES_START: "ADD_PURCHASES_START",
  ADD_PURCHASES_FINISH: "ADD_PURCHASES_FINISH",
  ADD_PURCHASES_CANCEL: "ADD_PURCHASES_CANCEL",
};

export default PurchasesActionTypes;
